CREATE SEQUENCE IF NOT EXISTS SEQ_RECIPIENTS MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 50 START WITH 1;

CREATE TABLE IF NOT EXISTS `TBL_RECIPIENTS` (
    `recipient_id`  BIGINT(19) PRIMARY KEY AUTO_INCREMENT,
    `name`          VARCHAR(255) NOT NULL,
    `email`         VARCHAR(255) NOT NULL,
    `phone_number`  VARCHAR(255) NOT NULL
);